# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemtracker < Formula
  desc "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  homepage "https://github.com/spaquet/gemtracker"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.5/gemtracker_1.0.5_darwin_amd64.tar.gz"
      sha256 "065023bfa4a1d7a7a147647f3ece6ab449a81b07d3127ccfd8d6bab10e36f144"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.5/gemtracker_1.0.5_darwin_arm64.tar.gz"
      sha256 "bb6f0091837ea6da53f27399d84c420bae80ea03032857275ea016e1fed2c957"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.5/gemtracker_1.0.5_linux_amd64.tar.gz"
      sha256 "ed7bfe6c3f021419f67f24e1b3275505ea8ecd599034a3248c74f5e85c3b72bc"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.5/gemtracker_1.0.5_linux_arm64.tar.gz"
      sha256 "b6953278e72e196ff5e32c467e4999651a1fa8181b3e024585d97806bb7454cc"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end
end
