# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemtracker < Formula
  desc "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  homepage "https://github.com/spaquet/gemtracker"
  version "1.0.2"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.2/gemtracker_1.0.2_darwin_amd64.tar.gz"
      sha256 "82ac691d2157f7906caea26a9da0e1a38dad536b4ac9630d4d34441a0d3ac3ba"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.2/gemtracker_1.0.2_darwin_arm64.tar.gz"
      sha256 "116716c42f48ce6327c6c14aac21b40231c980d3a01fe1113bf2f385eb9969c7"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.2/gemtracker_1.0.2_linux_amd64.tar.gz"
      sha256 "b1a0777453072f8cf425ffa1f0927ec68c691efd41229a7dcbb679ba9b23b11e"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.0.2/gemtracker_1.0.2_linux_arm64.tar.gz"
      sha256 "ce32bfb1676be30e61d54f78461a846a7b1c87a00354c9cb5f063a049c881e94"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  def caveats
    <<~EOS
      gemtracker analyzes Gemfile.lock files in Ruby projects.

      To use it:
        gemtracker
        gemtracker /path/to/project
    EOS
  end

  test do
    system "#{bin}/gemtracker", "--version"
  end
end
