# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "gemtracker" do
  version "1.2.0"

  on_intel do
    url "https://github.com/spaquet/gemtracker/releases/download/v1.2.0/gemtracker_1.2.0_darwin_amd64.tar.gz"
    sha256 "55be4ac26656dc92489fbe0f895d0e6083bffc857cc851eb48282ec5612db2db"
  end

  on_arm do
    url "https://github.com/spaquet/gemtracker/releases/download/v1.2.0/gemtracker_1.2.0_darwin_arm64.tar.gz"
    sha256 "0cdd148fb953ed277187e33e3e92daf8431235ed83a4c4aecb29a85c472d8f64"
  end

  homepage "https://github.com/spaquet/gemtracker"
  description "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  license "MIT"

  binary "gemtracker"

  test do
    system "#{staged_path}/gemtracker", "--version"
  end
end
