# This file was generated by GoReleaser. DO NOT EDIT.
cask "gemtracker" do
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/spaquet/gemtracker/releases/download/v#{version}/gemtracker_#{version}_darwin_amd64.tar.gz"
      sha256 "4f4ce58458df839cfe26114c444c0d192cf4997906f1958fe8bbb692ed029de1"
    end
    on_arm do
      url "https://github.com/spaquet/gemtracker/releases/download/v#{version}/gemtracker_#{version}_darwin_arm64.tar.gz"
      sha256 "30f9bf011c42e030bd786b575e0cad4b083d519955804901c5ffea455002b86d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/spaquet/gemtracker/releases/download/v#{version}/gemtracker_#{version}_linux_amd64.tar.gz"
      sha256 "03d475767cb1041fe9faea368da9741ff019cb4edf67d364e7825c2472d71ab5"
    end
    on_arm do
      url "https://github.com/spaquet/gemtracker/releases/download/v#{version}/gemtracker_#{version}_linux_arm64.tar.gz"
      sha256 "107afab8cedbfceab131a0d97ef7c6d024ec62e48c22b7ea3e375b5d46195b6c"
    end
  end

  name "gemtracker"
  desc "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  homepage "https://github.com/spaquet/gemtracker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gemtracker"

  # No zap stanza required

end
