# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemtracker < Formula
  desc "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  homepage "https://github.com/spaquet/gemtracker"
  version "1.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.1.6/gemtracker_1.1.6_darwin_amd64.tar.gz"
      sha256 "27770c80654cac4cc569f5209986ee55e35ba5bd5f3e8c58386b7e12cc423992"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.1.6/gemtracker_1.1.6_darwin_arm64.tar.gz"
      sha256 "40bd686fca5ed66519dc8e8334b1810c0f87c6622e9e29d79d4a19a6c96f8eca"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.1.6/gemtracker_1.1.6_linux_amd64.tar.gz"
      sha256 "b6c21a65c3c355ef7c62c146950e6f0b9e338aa1909d95d80f5295f51fd9d274"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.1.6/gemtracker_1.1.6_linux_arm64.tar.gz"
      sha256 "b89f524a1eede898c2ecd008c0368119b28ac5363df0152ab2399db5be6683b0"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  test do
    system "#{bin}/gemtracker", "--version"
  end
end
