# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemtracker < Formula
  desc "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  homepage "https://github.com/spaquet/gemtracker"
  version "1.2.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.2.12/gemtracker_1.2.12_darwin_amd64.tar.gz"
      sha256 "12fc678051502212e9d30cce94fdd6aad6de67aae09d2a2400fe1ebe1e0bf5f9"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.2.12/gemtracker_1.2.12_darwin_arm64.tar.gz"
      sha256 "bbe0cb2676e5b7babb01151415fa5239d55883d26c30ebc0ead3614a1963638c"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.2.12/gemtracker_1.2.12_linux_amd64.tar.gz"
      sha256 "8deb653d80952bee57b9080bf9564ab3af1c0275b996b656562a100e431915ff"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.2.12/gemtracker_1.2.12_linux_arm64.tar.gz"
      sha256 "b98f1de6ee7b7ca9b2fd9c06674ac4867493a2ce1a052c1ea6fb3b310b14b244"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  test do
    system "#{bin}/gemtracker", "--version"
  end
end
