# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemtracker < Formula
  desc "An interactive TUI for analyzing Ruby gem dependencies and security risks"
  homepage "https://github.com/spaquet/gemtracker"
  version "1.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.3.10/gemtracker_1.3.10_darwin_amd64.tar.gz"
      sha256 "453ead92e7316e1b091071dcbf42fc3fdaadb15e6511638e2a477a48fadf2196"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.3.10/gemtracker_1.3.10_darwin_arm64.tar.gz"
      sha256 "48c624fc88b6bf4040da480c5403a0108c1cac72594cd8309114a9dd93bd0145"

      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.3.10/gemtracker_1.3.10_linux_amd64.tar.gz"
      sha256 "7fdb4eb05d057552be7a35fa7b5adfa61231bfc261cf42b2a11d923a5c42cae8"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spaquet/gemtracker/releases/download/v1.3.10/gemtracker_1.3.10_linux_arm64.tar.gz"
      sha256 "2670299df9f1ce46a7e629fd8684d8905e878da6c135af6bf9a965234366d7e5"
      define_method(:install) do
        bin.install "gemtracker"
      end
    end
  end

  test do
    system "#{bin}/gemtracker", "--version"
  end
end
